apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-network-multitool-daemonset
  namespace: default
spec:
  selector:
    matchLabels:
      name: network-multitool
  template:
    metadata:
      labels:
        name: network-multitool
    spec:
      containers:
      - name: network-multitool
        image: praqma/network-multitool
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi

